[package]
name = "qrrs"
version = "0.1.0"
authors = ["Lenivaya <xocada@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qrcode = "0.11"
bardecoder = "0.2.2"
image = "0.22"
clap = "2.33"
