[package]
name = "qrrs"
version = "0.1.1"
authors = ["Lenivaya <xocada@gmail.com>"]
description = "CLI QR code generator and reader"
homepage = "https://github.com/Lenivaya/qrrs"
repository = "https://github.com/Lenivaya/qrrs"
readme = "README.md"
keywords = ["cli", "qrcode", "qr", "QR"]
categories = ["command-line-utilities", "encoding"]
license = "MIT"
edition = "2018"

[dependencies]
qrcode = "0.11"
bardecoder = "0.2.2"
image = "0.22"
clap = "2.33"
rand = "0.7"
