[package]
name = "qrrs"
version = "0.1.4"
authors = ["Lenivaya <xocada@gmail.com>"]
description = "CLI QR code generator and reader"
homepage = "https://github.com/Lenivaya/qrrs"
repository = "https://github.com/Lenivaya/qrrs"
readme = "README.md"
keywords = ["cli", "qr-code", "qr", "decoder", "parser"]
categories = ["command-line-utilities", "encoding", "parsing"]
license = "MIT"
edition = "2018"

[dependencies]
qrcode = "0.12.0"
rqrr = "0.3.2"
image = "0.23"
clap = "2.33.3"

[dev-dependencies]
rand = "0.8.3"
predicates = "1"
assert_cmd = "1"
