name: CI

on:
  push:
    branches:
      - master
    tags-ignore: ["v[0-9]+.[0-9]+.[0-9]+*"]
  pull_request:
    branches:
      - "*"
    tags-ignore: ["v[0-9]+.[0-9]+.[0-9]+*"]

jobs:
  format:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #  - uses: actions-rs/toolchain@v1
      #     with:
      #       toolchain: nightly
      #       components: rustfmt, clippy
      #       override: true

      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup environment
        run: nix develop

      - name: Format project source code
        run: nix fmt

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      # - uses: mbrobbel/rustfmt-check@master
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
