name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Build
        run: cargo build --release --verbose --all --locked

      - name: Test
        run: cargo test --verbose --all

      - name: Clippy
        run: cargo clippy --all-targets --all-features

      - name: Format
        run: cargo fmt -- --check
