name: Test

on:
  push:
    branches:
      - master
    tags-ignore: ["v[0-9]+.[0-9]+.[0-9]+*"]
    paths:
      - "**.rs"
      - "Cargo*"
      - ".github/workflows/**.yml"
      - ".github/.codecov.yml"
  pull_request:
    branches:
      - "*"
    tags-ignore: ["v[0-9]+.[0-9]+.[0-9]+*"]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --all

  code_coverage:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup environment
        run: nix develop

      - name: Generate coverage report
        run: nix develop .#coverage --command cargo tarpaulin --out Xml

        # - name: Generate coverage report
        #   uses: actions-rs/tarpaulin@v0.1
        #   with:
        #     version: "0.22.0"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          fail_ci_if_error: true
