name: Test

on:
  push:
    branches:
      - master
    tags-ignore: ["v[0-9]+.[0-9]+.[0-9]+*"]
    paths:
      - "**.rs"
      - "Cargo*"
      - ".github/workflows/**.yml"
      - ".github/.codecov.yml"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v10

      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v4

      - name: Test
        run: nix develop --command cargo test --verbose --all

  code_coverage:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v10

      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v4

      - name: Setup environment
        run: nix develop

      - name: Generate coverage report
        run: nix develop --command cargo tarpaulin --out xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          fail_ci_if_error: true
